#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.toml

version = 2
final_space = true
console_title_template = "{{if .Root}}(Admin){{end}} {{.PWD}}"
patch_pwsh_bleed = true


[palette]
# Base colors
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111B"

# Text colors
text = "#CDD6F4"
subtext0 = "#A6ADC8"
subtext1 = "#BAC2DE"

# Overlay colors
overlay0 = "#6C7086"
overlay1 = "#7F849C"
overlay2 = "#9399B2"

# Surface colors
surface0 = "#313244"
surface1 = "#45475A"
surface2 = "#585B70"

# Core colors
lavender = "#B4BEFE"
blue = "#89B4FA"
sapphire = "#74C7EC"
sky = "#89DCEB"
teal = "#94E2D5"
green = "#A6E3A1"
yellow = "#F9E2AF"
peach = "#FAB387"
maroon = "#EBA0AC"
red = "#F38BA8"
mauve = "#CBA6F7"
pink = "#F5C2E7"
flamingo = "#F2CDCD"
rosewater = "#F5E0DC"

# Bright variants
brightBlue = "#89B4FA"
brightGreen = "#A6E3A1"
brightCyan = "#94E2D5"
brightRed = "#F38BA8"
brightMagenta = "#F5C2E7"
brightYellow = "#F9E2AF"
brightWhite = "#CDD6F4"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground = "p:sapphire"
  template = "{{ .Path }}"

  [blocks.segments.properties]
  style = "full"
  max_depth = 3

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:lavender"
  background = "transparent"
  template = " {{ .HEAD }}{{ if .Working.Changed }} <p:peach>≢</>{{ end }}{{ if .Staging.Changed }} <p:green>*</>{{ end }}"
  [blocks.segments.properties]
    branch_icon = ""
    fetch_status = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true
  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:mauve"
  background = "transparent"
  template = "❯"

[transient_prompt]
foreground = "p:flamingo"
background = "transparent"
template = "❯ "

[secondary_prompt]
foreground = "p:rosewater"
background = "transparent"
template = "❯❯ "
