version = 2
final_space = true
console_title_template = "{{if .Root}}(Admin){{end}} {{.PWD}}"

[palette]
base = "#191724"
surface = "#1e1e2e"
overlay = "#2c2a3e"
pine = "#9ccfd8"
foam = "#a6e3e9"
rose = "#f38ba8"
gold = "#fab387"
mauve = "#cba6f7"
sky = "#89dceb"
emerald = "#a6e3a1"
lavender = "#b4befe"
text = "#e0def4"
subtext1 = "#cdd6f4"
subtext0 = "#6e6a86"

[[blocks]]
type = "prompt"
alignment = "left"
newline = false

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:foam"
  template = "{{ .Path }} "

  [blocks.segments.properties]
  style = "full"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "#6C6C6C"
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#FFAFD7>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "

[blocks.segments.properties]
branch_ahead_icon = "⇡  "
branch_behind_icon = "⇣  "
branch_icon = ""
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
github_icon = ""

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:rose"
  background = "transparent"
  template = "❯ "

[transient_prompt]
foreground = "p:mauve"
template = "❯ "

[secondary_prompt]
foreground = "p:subtext1"
template = "❯❯ "

